version: "3.9"

services:
  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    ports:
      - "9000:9000"

    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grpc-server
    restart: always
    ports:
      - "50051:50051"
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
    depends_on:
      - clickhouse