// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: analytics.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Analytics_GetUniqueUsers_FullMethodName = "/grpc.Analytics/GetUniqueUsers"
	Analytics_GetPageViews_FullMethodName   = "/grpc.Analytics/GetPageViews"
	Analytics_GetTopPages_FullMethodName    = "/grpc.Analytics/GetTopPages"
)

// AnalyticsClient is the client API for Analytics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsClient interface {
	GetUniqueUsers(ctx context.Context, in *UniqueUsersRequest, opts ...grpc.CallOption) (*UniqueUsersResponse, error)
	GetPageViews(ctx context.Context, in *PageViewsRequest, opts ...grpc.CallOption) (*PageViewsResponse, error)
	GetTopPages(ctx context.Context, in *TopPagesRequest, opts ...grpc.CallOption) (*TopPagesResponse, error)
}

type analyticsClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsClient(cc grpc.ClientConnInterface) AnalyticsClient {
	return &analyticsClient{cc}
}

func (c *analyticsClient) GetUniqueUsers(ctx context.Context, in *UniqueUsersRequest, opts ...grpc.CallOption) (*UniqueUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UniqueUsersResponse)
	err := c.cc.Invoke(ctx, Analytics_GetUniqueUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsClient) GetPageViews(ctx context.Context, in *PageViewsRequest, opts ...grpc.CallOption) (*PageViewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PageViewsResponse)
	err := c.cc.Invoke(ctx, Analytics_GetPageViews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsClient) GetTopPages(ctx context.Context, in *TopPagesRequest, opts ...grpc.CallOption) (*TopPagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopPagesResponse)
	err := c.cc.Invoke(ctx, Analytics_GetTopPages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServer is the server API for Analytics service.
// All implementations must embed UnimplementedAnalyticsServer
// for forward compatibility.
type AnalyticsServer interface {
	GetUniqueUsers(context.Context, *UniqueUsersRequest) (*UniqueUsersResponse, error)
	GetPageViews(context.Context, *PageViewsRequest) (*PageViewsResponse, error)
	GetTopPages(context.Context, *TopPagesRequest) (*TopPagesResponse, error)
	mustEmbedUnimplementedAnalyticsServer()
}

// UnimplementedAnalyticsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServer struct{}

func (UnimplementedAnalyticsServer) GetUniqueUsers(context.Context, *UniqueUsersRequest) (*UniqueUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUniqueUsers not implemented")
}
func (UnimplementedAnalyticsServer) GetPageViews(context.Context, *PageViewsRequest) (*PageViewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPageViews not implemented")
}
func (UnimplementedAnalyticsServer) GetTopPages(context.Context, *TopPagesRequest) (*TopPagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopPages not implemented")
}
func (UnimplementedAnalyticsServer) mustEmbedUnimplementedAnalyticsServer() {}
func (UnimplementedAnalyticsServer) testEmbeddedByValue()                   {}

// UnsafeAnalyticsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServer will
// result in compilation errors.
type UnsafeAnalyticsServer interface {
	mustEmbedUnimplementedAnalyticsServer()
}

func RegisterAnalyticsServer(s grpc.ServiceRegistrar, srv AnalyticsServer) {
	// If the following call pancis, it indicates UnimplementedAnalyticsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Analytics_ServiceDesc, srv)
}

func _Analytics_GetUniqueUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UniqueUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServer).GetUniqueUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Analytics_GetUniqueUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServer).GetUniqueUsers(ctx, req.(*UniqueUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analytics_GetPageViews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageViewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServer).GetPageViews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Analytics_GetPageViews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServer).GetPageViews(ctx, req.(*PageViewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analytics_GetTopPages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopPagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServer).GetTopPages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Analytics_GetTopPages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServer).GetTopPages(ctx, req.(*TopPagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Analytics_ServiceDesc is the grpc.ServiceDesc for Analytics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Analytics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Analytics",
	HandlerType: (*AnalyticsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUniqueUsers",
			Handler:    _Analytics_GetUniqueUsers_Handler,
		},
		{
			MethodName: "GetPageViews",
			Handler:    _Analytics_GetPageViews_Handler,
		},
		{
			MethodName: "GetTopPages",
			Handler:    _Analytics_GetTopPages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics.proto",
}
